### ISSUE TITLE
When trying to use accelerate, I get this error

### ISSUE THREAD

**Issue by rikabi89** [yl4579/StyleTTS2#124]
```
(styleTTS2) H:\StyleTTS2>accelerate launch --mixed_precision=fp16 train_finetune_accelerate.py --config_path ./Configs/config_ft2.yml
bert loaded
bert_encoder loaded
predictor loaded
decoder loaded
text_encoder loaded
predictor_encoder loaded
style_encoder loaded
diffusion loaded
text_aligner loaded
pitch_extractor loaded
mpd loaded
msd loaded
wd loaded
BERT AdamW (
Parameter Group 0
    amsgrad: False
    base_momentum: 0.85
    betas: (0.9, 0.99)
    capturable: False
    eps: 1e-09
    foreach: None
    initial_lr: 1e-05
    lr: 1e-05
    max_lr: 2e-05
    max_momentum: 0.95
    maximize: False
    min_lr: 0
    weight_decay: 0.01
)
decoder AdamW (
Parameter Group 0
    amsgrad: False
    base_momentum: 0.85
    betas: (0.0, 0.99)
    capturable: False
    eps: 1e-09
    foreach: None
    initial_lr: 0.0001
    lr: 0.0001
    max_lr: 0.0002
    max_momentum: 0.95
    maximize: False
    min_lr: 0
    weight_decay: 0.0001
)
Traceback (most recent call last):
  File "train_finetune_accelerate.py", line 713, in <module>
    main()
  File "H:\anaconda3\envs\styleTTS2\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "H:\anaconda3\envs\styleTTS2\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "H:\anaconda3\envs\styleTTS2\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "H:\anaconda3\envs\styleTTS2\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "train_finetune_accelerate.py", line 253, in main
    _ = [model[key].eval() for key in model]
  File "train_finetune_accelerate.py", line 253, in <listcomp>
    _ = [model[key].eval() for key in model]
AttributeError: 'bool' object has no attribute 'eval'
Traceback (most recent call last):
  File "H:\anaconda3\envs\styleTTS2\Scripts\accelerate-script.py", line 9, in <module>
    sys.exit(main())
  File "H:\anaconda3\envs\styleTTS2\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "H:\anaconda3\envs\styleTTS2\lib\site-packages\accelerate\commands\launch.py", line 941, in launch_command
    simple_launcher(args)
  File "H:\anaconda3\envs\styleTTS2\lib\site-packages\accelerate\commands\launch.py", line 603, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['H:\\anaconda3\\envs\\styleTTS2\\python.exe', 'train_finetune_accelerate.py', '--config_path', './Configs/config_ft2.yml']' returned non-zero exit status 1.

(styleTTS2) H:\StyleTTS2>
```
Win11 Anaconda
Works fine without acerate but again is mega slow

**Comment by korakoe** [comment]
working on it

**Comment by Bonk1971** [comment]
I have the same issue.

**Comment by YJCmote1** [comment]
@yl4579 Sorry for bothering, Could I ask if the bug is fixed right now? I still have the same issue.

**Comment by yl4579** [comment]
@YJCmote1 I think @korakoe is the one working on it because I don’t have a windows environment available to test the code.

**Comment by YJCmote1** [comment]
@yl4579 thanks for your reply. And I'm looking forward that this issue can be fixed as soon as possible.

**Comment by rikabi89** [comment]
I should note this not works thank to ButterCreams fix and using WSL rather than Anaconda
