### ISSUE TITLE
Finetune error on Colab

### ISSUE THREAD

**Issue by martinambrus** [yl4579/StyleTTS2#133]
Trying the Colab Notebook for finetuning, I'm getting the following error with a custom set of ~1000 WAV files (so not the archive with 200 LJSpeech samples by my own set):

```


2023-12-06 21:18:55.383647: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-12-06 21:18:55.383708: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-12-06 21:18:55.383752: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2023-12-06 21:18:55.392753: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-12-06 21:18:56.646248: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Some weights of the model checkpoint at microsoft/wavlm-base-plus were not used when initializing WavLMModel: ['encoder.pos_conv_embed.conv.weight_v', 'encoder.pos_conv_embed.conv.weight_g']
- This IS expected if you are initializing WavLMModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing WavLMModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of WavLMModel were not initialized from the model checkpoint at microsoft/wavlm-base-plus and are newly initialized: ['encoder.pos_conv_embed.conv.parametrizations.weight.original0', 'encoder.pos_conv_embed.conv.parametrizations.weight.original1']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
bert loaded
bert_encoder loaded
predictor loaded
decoder loaded
text_encoder loaded
predictor_encoder loaded
style_encoder loaded
diffusion loaded
text_aligner loaded
pitch_extractor loaded
mpd loaded
msd loaded
wd loaded
BERT AdamW (
Parameter Group 0
    amsgrad: False
    base_momentum: 0.85
    betas: (0.9, 0.99)
    capturable: False
    differentiable: False
    eps: 1e-09
    foreach: None
    fused: None
    initial_lr: 1e-05
    lr: 1e-05
    max_lr: 2e-05
    max_momentum: 0.95
    maximize: False
    min_lr: 0
    weight_decay: 0.01
)
decoder AdamW (
Parameter Group 0
    amsgrad: False
    base_momentum: 0.85
    betas: (0.0, 0.99)
    capturable: False
    differentiable: False
    eps: 1e-09
    foreach: None
    fused: None
    initial_lr: 0.0001
    lr: 0.0001
    max_lr: 0.0002
    max_momentum: 0.95
    maximize: False
    min_lr: 0
    weight_decay: 0.0001
)
vˈeɪnli tɹˈaɪɪŋ tə ɹᵻkˈʌvɚɹ ɐ ʃɹˈɛd ʌv maɪ dˈɪɡnᵻɾi , aɪ fɚbˈeɪd maɪsˈɛlf tə ɹˈʌb ɪɾ æz aɪ stɹˈeɪtənd ˈʌp , pˈeɪstᵻd ˌɔn ɐ smˈaɪl , ænd tˈɜːnd təwˈɔːɹd ðə sˈoːɹs ʌvðə vˈɔɪs , ɹᵻplˈaɪɪŋ , `` jˈɛs , sˌɜː . dʒˈʌst pˌʊt jʊɹ ɡɹˈoʊsɚɹiz ɔnðə bˈɛlt . ''
vˈeɪnli tɹˈaɪɪŋ tə ɹᵻkˈʌvɚɹ ɐ ʃɹˈɛd ʌv maɪ dˈɪɡnᵻɾi , aɪ fɚbˈeɪd maɪsˈɛlf tə ɹˈʌb ɪɾ æz aɪ stɹˈeɪtənd ˈʌp , pˈeɪstᵻd ˌɔn ɐ smˈaɪl , ænd tˈɜːnd təwˈɔːɹd ðə sˈoːɹs ʌvðə vˈɔɪs , ɹᵻplˈaɪɪŋ , `` jˈɛs , sˌɜː . dʒˈʌst pˌʊt jʊɹ ɡɹˈoʊsɚɹiz ɔnðə bˈɛlt . ''
Epoch [1/50], Step [10/425], Loss: 0.39932, Disc Loss: 3.75799, Dur Loss: 0.53232, CE Loss: 0.02488, Norm Loss: 0.68743, F0 Loss: 1.20466, LM Loss: 1.32038, Gen Loss: 7.28315, Sty Loss: 0.00000, Diff Loss: 0.00000, DiscLM Loss: 0.00000, GenLM Loss: 0.00000, SLoss: 0.00000, S2S Loss: 0.67225, Mono Loss: 0.15302
Time elasped: 22.386781930923462
Epoch [1/50], Step [20/425], Loss: 0.38406, Disc Loss: 3.82827, Dur Loss: 0.48177, CE Loss: 0.02522, Norm Loss: 0.74138, F0 Loss: 1.53995, LM Loss: 1.13913, Gen Loss: 6.22224, Sty Loss: 0.00000, Diff Loss: 0.00000, DiscLM Loss: 0.00000, GenLM Loss: 0.00000, SLoss: 0.00000, S2S Loss: 0.35177, Mono Loss: 0.07727
Time elasped: 43.56470513343811
Epoch [1/50], Step [30/425], Loss: 0.40314, Disc Loss: 3.83704, Dur Loss: 0.48359, CE Loss: 0.02320, Norm Loss: 0.55668, F0 Loss: 1.43795, LM Loss: 0.99343, Gen Loss: 7.15864, Sty Loss: 0.00000, Diff Loss: 0.00000, DiscLM Loss: 0.00000, GenLM Loss: 0.00000, SLoss: 0.00000, S2S Loss: 0.30775, Mono Loss: 0.10054
Time elasped: 64.82571959495544
ðɛɹwˌʌz ɐ lˈɔŋ , ɛmbˈæɹəst pˈɔːz bᵻfˌoːɹ maɪ lˈɪv ɪn fiˈɑːnsˈeɪ ˈæskt , `` hˌaʊ dˈɪd juː nˈoʊ ɪt wʌz mˌiː ? ''
ðɛɹwˌʌz ɐ lˈɔŋ , ɛmbˈæɹəst pˈɔːz bᵻfˌoːɹ maɪ lˈɪv ɪn fiˈɑːnsˈeɪ ˈæskt , `` hˌaʊ dˈɪd juː nˈoʊ ɪt wʌz mˌiː ? ''
hiː wʌz ˈoʊnli blˈɑːkɪŋ hɪmsˈɛlf ɐɡˈɛnst fˈeɪ ˈaɪz . hiː nˈuː hiː wʌz bˌiːɪŋ tɹˈeɪld . `` dˈæm , '' aɪ wˈɪspɚd ænd dɹˈɑːpt ðə bˈɑːɾəl .
hiː wʌz ˈoʊnli blˈɑːkɪŋ hɪmsˈɛlf ɐɡˈɛnst fˈeɪ ˈaɪz . hiː nˈuː hiː wʌz bˌiːɪŋ tɹˈeɪld . `` dˈæm , '' aɪ wˈɪspɚd ænd dɹˈɑːpt ðə bˈɑːɾəl .
kˈɛɹfəl tə kˈiːp ðɪ ɛɡzˈɔːstʃən ˌaʊɾəv maɪ vˈɔɪs , aɪ ˈæskt , `` ɹˈiəli ʃˈʊɹ ? ''
kˈɛɹfəl tə kˈiːp ðɪ ɛɡzˈɔːstʃən ˌaʊɾəv maɪ vˈɔɪs , aɪ ˈæskt , `` ɹˈiəli ʃˈʊɹ ? ''
aɪ wʌz stˈɑːɹɾɪŋ tə θˈɪŋk ðə mˈɛsɪdʒ hæd ˈɛndᵻd wɛn ʃiː kəntˈɪnjuːd , sˈɔftli , `` fˈaɪnd ˈaʊt hˌuː dˈɪd ɪt , tˈoʊbi , plˈiːz . mˌeɪk ʃˈʊɹ ðeɪ dˈoʊnt wˈɪn . ɪf juː wɜːɹ ˈɛvɚ maɪ fɹˈɛnd , tˈoʊbi , plˈiːz ... ``
aɪ wʌz stˈɑːɹɾɪŋ tə θˈɪŋk ðə mˈɛsɪdʒ hæd ˈɛndᵻd wɛn ʃiː kəntˈɪnjuːd , sˈɔftli , `` fˈaɪnd ˈaʊt hˌuː dˈɪd ɪt , tˈoʊbi , plˈiːz . mˌeɪk ʃˈʊɹ ðeɪ dˈoʊnt wˈɪn . ɪf juː wɜːɹ ˈɛvɚ maɪ fɹˈɛnd , tˈoʊbi , plˈiːz ... ``
aɪ wʌz stˈɑːɹɾɪŋ tə θˈɪŋk ðə mˈɛsɪdʒ hæd ˈɛndᵻd wɛn ʃiː kəntˈɪnjuːd , sˈɔftli , `` fˈaɪnd ˈaʊt hˌuː dˈɪd ɪt , tˈoʊbi , plˈiːz . mˌeɪk ʃˈʊɹ ðeɪ dˈoʊnt wˈɪn . ɪf juː wɜːɹ ˈɛvɚ maɪ fɹˈɛnd , tˈoʊbi , plˈiːz ... ``
aɪ wʌz stˈɑːɹɾɪŋ tə θˈɪŋk ðə mˈɛsɪdʒ hæd ˈɛndᵻd wɛn ʃiː kəntˈɪnjuːd , sˈɔftli , `` fˈaɪnd ˈaʊt hˌuː dˈɪd ɪt , tˈoʊbi , plˈiːz . mˌeɪk ʃˈʊɹ ðeɪ dˈoʊnt wˈɪn . ɪf juː wɜːɹ ˈɛvɚ maɪ fɹˈɛnd , tˈoʊbi , plˈiːz ... ``
Epoch [1/50], Step [40/425], Loss: 0.34131, Disc Loss: 3.67051, Dur Loss: 0.54063, CE Loss: 0.02715, Norm Loss: 1.26384, F0 Loss: 3.21374, LM Loss: 1.44737, Gen Loss: 7.82895, Sty Loss: 0.00000, Diff Loss: 0.00000, DiscLM Loss: 0.00000, GenLM Loss: 0.00000, SLoss: 0.00000, S2S Loss: 0.15853, Mono Loss: 0.04745
Time elasped: 86.35610175132751
ðɛɹwˌʌz ɐ lˈɔŋ , ɛmbˈæɹəst pˈɔːz bᵻfˌoːɹ maɪ lˈɪv ɪn fiˈɑːnsˈeɪ ˈæskt , `` hˌaʊ dˈɪd juː nˈoʊ ɪt wʌz mˌiː ? ''
ðɛɹwˌʌz ɐ lˈɔŋ , ɛmbˈæɹəst pˈɔːz bᵻfˌoːɹ maɪ lˈɪv ɪn fiˈɑːnsˈeɪ ˈæskt , `` hˌaʊ dˈɪd juː nˈoʊ ɪt wʌz mˌiː ? ''
Epoch [1/50], Step [50/425], Loss: 0.38911, Disc Loss: 3.81474, Dur Loss: 0.63803, CE Loss: 0.03350, Norm Loss: 0.54204, F0 Loss: 1.63608, LM Loss: 1.10622, Gen Loss: 7.26892, Sty Loss: 0.00000, Diff Loss: 0.00000, DiscLM Loss: 0.00000, GenLM Loss: 0.00000, SLoss: 0.00000, S2S Loss: 0.59619, Mono Loss: 0.03372
Time elasped: 109.06479406356812
hiː wʌz ˈoʊnli blˈɑːkɪŋ hɪmsˈɛlf ɐɡˈɛnst fˈeɪ ˈaɪz . hiː nˈuː hiː wʌz bˌiːɪŋ tɹˈeɪld . `` dˈæm , '' aɪ wˈɪspɚd ænd dɹˈɑːpt ðə bˈɑːɾəl .
hiː wʌz ˈoʊnli blˈɑːkɪŋ hɪmsˈɛlf ɐɡˈɛnst fˈeɪ ˈaɪz . hiː nˈuː hiː wʌz bˌiːɪŋ tɹˈeɪld . `` dˈæm , '' aɪ wˈɪspɚd ænd dɹˈɑːpt ðə bˈɑːɾəl .
aɪ hæd ɐ tˈaɪɾəl , wˈʌn ðæt hæd klˈɪɹli bˌɪn ɐwˈɔːɹdᵻd tə mˌiː fɔːɹ mˈɛɹɪt , ɹˈæðɚ ðɐn ˌaʊɾəv kˈɜːɾəsi , ɪf aɪ wʌz ɪnsˈɪstɪŋ ɔnðə jˈuːs ʌv `` sˌɜː '' ˈoʊvɚ `` lˈeɪdi . ''
aɪ hæd ɐ tˈaɪɾəl , wˈʌn ðæt hæd klˈɪɹli bˌɪn ɐwˈɔːɹdᵻd tə mˌiː fɔːɹ mˈɛɹɪt , ɹˈæðɚ ðɐn ˌaʊɾəv kˈɜːɾəsi , ɪf aɪ wʌz ɪnsˈɪstɪŋ ɔnðə jˈuːs ʌv `` sˌɜː '' ˈoʊvɚ `` lˈeɪdi . ''
aɪ hæd ɐ tˈaɪɾəl , wˈʌn ðæt hæd klˈɪɹli bˌɪn ɐwˈɔːɹdᵻd tə mˌiː fɔːɹ mˈɛɹɪt , ɹˈæðɚ ðɐn ˌaʊɾəv kˈɜːɾəsi , ɪf aɪ wʌz ɪnsˈɪstɪŋ ɔnðə jˈuːs ʌv `` sˌɜː '' ˈoʊvɚ `` lˈeɪdi . ''
aɪ hæd ɐ tˈaɪɾəl , wˈʌn ðæt hæd klˈɪɹli bˌɪn ɐwˈɔːɹdᵻd tə mˌiː fɔːɹ mˈɛɹɪt , ɹˈæðɚ ðɐn ˌaʊɾəv kˈɜːɾəsi , ɪf aɪ wʌz ɪnsˈɪstɪŋ ɔnðə jˈuːs ʌv `` sˌɜː '' ˈoʊvɚ `` lˈeɪdi . ''
lˈiːnɪŋ fˈɔːɹwɚd , sˈaɪmən pɹˈɛst ɐ kˈɪs ɐɡˈɛnst maɪ fˈɔːɹhɛd ænd wˈɪspɚd , `` aɪl mˌeɪk ʃˈʊɹ sˈʌmwʌn fˈaɪndz jʊɹ kˈɑːɹ ɪn ɐ wˈiːk ɔːɹ tˈuː , wˈʌns ðeɪɚ ɹˈɛdi tə ɡˈɪv ˌʌp hˈoʊp . wˈʊdənt dˈuː tə mˌeɪk jʊɹ fˈæmɪli wˈeɪt fɔːɹ juː tˈuː lˈɔŋ , nˈaʊ , wˈʊd ɪt ? ''
lˈiːnɪŋ fˈɔːɹwɚd , sˈaɪmən pɹˈɛst ɐ kˈɪs ɐɡˈɛnst maɪ fˈɔːɹhɛd ænd wˈɪspɚd , `` aɪl mˌeɪk ʃˈʊɹ sˈʌmwʌn fˈaɪndz jʊɹ kˈɑːɹ ɪn ɐ wˈiːk ɔːɹ tˈuː , wˈʌns ðeɪɚ ɹˈɛdi tə ɡˈɪv ˌʌp hˈoʊp . wˈʊdənt dˈuː tə mˌeɪk jʊɹ fˈæmɪli wˈeɪt fɔːɹ juː tˈuː lˈɔŋ , nˈaʊ , wˈʊd ɪt ? ''
Epoch [1/50], Step [60/425], Loss: 0.37751, Disc Loss: 3.83283, Dur Loss: 0.57051, CE Loss: 0.03174, Norm Loss: 0.65469, F0 Loss: 2.57278, LM Loss: 1.05728, Gen Loss: 6.43352, Sty Loss: 0.00000, Diff Loss: 0.00000, DiscLM Loss: 0.00000, GenLM Loss: 0.00000, SLoss: 0.00000, S2S Loss: 0.16396, Mono Loss: 0.05835
Time elasped: 133.02892351150513
aɪ lˈʊk klˈoʊsɚ tə hjˈuːmən ðˌænə lˈɑːt ʌv tʃˈeɪndʒlɪŋz dˈuː , bˌʌt `` klˈoʊs '' dˈʌzənt kˈʌt ɪɾ ɔnðə stɹˈiːts əvə hjˈuːmən sˈɪɾi .
aɪ lˈʊk klˈoʊsɚ tə hjˈuːmən ðˌænə lˈɑːt ʌv tʃˈeɪndʒlɪŋz dˈuː , bˌʌt `` klˈoʊs '' dˈʌzənt kˈʌt ɪɾ ɔnðə stɹˈiːts əvə hjˈuːmən sˈɪɾi .
aɪ hæd ɐ tˈaɪɾəl , wˈʌn ðæt hæd klˈɪɹli bˌɪn ɐwˈɔːɹdᵻd tə mˌiː fɔːɹ mˈɛɹɪt , ɹˈæðɚ ðɐn ˌaʊɾəv kˈɜːɾəsi , ɪf aɪ wʌz ɪnsˈɪstɪŋ ɔnðə jˈuːs ʌv `` sˌɜː '' ˈoʊvɚ `` lˈeɪdi . ''
aɪ hæd ɐ tˈaɪɾəl , wˈʌn ðæt hæd klˈɪɹli bˌɪn ɐwˈɔːɹdᵻd tə mˌiː fɔːɹ mˈɛɹɪt , ɹˈæðɚ ðɐn ˌaʊɾəv kˈɜːɾəsi , ɪf aɪ wʌz ɪnsˈɪstɪŋ ɔnðə jˈuːs ʌv `` sˌɜː '' ˈoʊvɚ `` lˈeɪdi . ''
aɪ hæd ɐ tˈaɪɾəl , wˈʌn ðæt hæd klˈɪɹli bˌɪn ɐwˈɔːɹdᵻd tə mˌiː fɔːɹ mˈɛɹɪt , ɹˈæðɚ ðɐn ˌaʊɾəv kˈɜːɾəsi , ɪf aɪ wʌz ɪnsˈɪstɪŋ ɔnðə jˈuːs ʌv `` sˌɜː '' ˈoʊvɚ `` lˈeɪdi . ''
aɪ hæd ɐ tˈaɪɾəl , wˈʌn ðæt hæd klˈɪɹli bˌɪn ɐwˈɔːɹdᵻd tə mˌiː fɔːɹ mˈɛɹɪt , ɹˈæðɚ ðɐn ˌaʊɾəv kˈɜːɾəsi , ɪf aɪ wʌz ɪnsˈɪstɪŋ ɔnðə jˈuːs ʌv `` sˌɜː '' ˈoʊvɚ `` lˈeɪdi . ''
lˈiːnɪŋ fˈɔːɹwɚd , sˈaɪmən pɹˈɛst ɐ kˈɪs ɐɡˈɛnst maɪ fˈɔːɹhɛd ænd wˈɪspɚd , `` aɪl mˌeɪk ʃˈʊɹ sˈʌmwʌn fˈaɪndz jʊɹ kˈɑːɹ ɪn ɐ wˈiːk ɔːɹ tˈuː , wˈʌns ðeɪɚ ɹˈɛdi tə ɡˈɪv ˌʌp hˈoʊp . wˈʊdənt dˈuː tə mˌeɪk jʊɹ fˈæmɪli wˈeɪt fɔːɹ juː tˈuː lˈɔŋ , nˈaʊ , wˈʊd ɪt ? ''
lˈiːnɪŋ fˈɔːɹwɚd , sˈaɪmən pɹˈɛst ɐ kˈɪs ɐɡˈɛnst maɪ fˈɔːɹhɛd ænd wˈɪspɚd , `` aɪl mˌeɪk ʃˈʊɹ sˈʌmwʌn fˈaɪndz jʊɹ kˈɑːɹ ɪn ɐ wˈiːk ɔːɹ tˈuː , wˈʌns ðeɪɚ ɹˈɛdi tə ɡˈɪv ˌʌp hˈoʊp . wˈʊdənt dˈuː tə mˌeɪk jʊɹ fˈæmɪli wˈeɪt fɔːɹ juː tˈuː lˈɔŋ , nˈaʊ , wˈʊd ɪt ? ''
Epoch [1/50], Step [70/425], Loss: 0.38313, Disc Loss: 3.69411, Dur Loss: 0.38770, CE Loss: 0.01693, Norm Loss: 0.44408, F0 Loss: 1.45658, LM Loss: 1.05754, Gen Loss: 7.03299, Sty Loss: 0.00000, Diff Loss: 0.00000, DiscLM Loss: 0.00000, GenLM Loss: 0.00000, SLoss: 0.00000, S2S Loss: 0.08302, Mono Loss: 0.10683
Time elasped: 155.60852193832397
ðə smˈɛl ʌv mˈædʒɪk kæn kˈʌt əkɹˌɑːs ˈɔːlmoʊst ˈɛnɪθˌɪŋ ˈɛls , ænd sˈɪns ˈɛvɹi kˈæstɚ hɐz ðɛɹ ˈoʊn mˈædʒɪkəl `` tˈeɪst , '' ɪɾ ˈɔːlsoʊ sˈɜːvz æz ɐ sˈɪɡnɪtʃɚɹ ʌv sˈɔːɹts .
ðə smˈɛl ʌv mˈædʒɪk kæn kˈʌt əkɹˌɑːs ˈɔːlmoʊst ˈɛnɪθˌɪŋ ˈɛls , ænd sˈɪns ˈɛvɹi kˈæstɚ hɐz ðɛɹ ˈoʊn mˈædʒɪkəl `` tˈeɪst , '' ɪɾ ˈɔːlsoʊ sˈɜːvz æz ɐ sˈɪɡnɪtʃɚɹ ʌv sˈɔːɹts .
Epoch [1/50], Step [80/425], Loss: 0.32922, Disc Loss: 3.85990, Dur Loss: 0.79580, CE Loss: 0.03912, Norm Loss: 1.00585, F0 Loss: 2.19026, LM Loss: 1.15833, Gen Loss: 5.64358, Sty Loss: 0.00000, Diff Loss: 0.00000, DiscLM Loss: 0.00000, GenLM Loss: 0.00000, SLoss: 0.00000, S2S Loss: 0.23845, Mono Loss: 0.03946
Time elasped: 176.6677861213684
Epoch [1/50], Step [90/425], Loss: 0.36406, Disc Loss: 3.82590, Dur Loss: 0.74693, CE Loss: 0.03957, Norm Loss: 0.47212, F0 Loss: 1.42239, LM Loss: 1.05322, Gen Loss: 6.92990, Sty Loss: 0.00000, Diff Loss: 0.00000, DiscLM Loss: 0.00000, GenLM Loss: 0.00000, SLoss: 0.00000, S2S Loss: 0.09054, Mono Loss: 0.12456
Time elasped: 200.01792573928833
Traceback (most recent call last):
  File "/content/StyleTTS2/train_finetune.py", line 707, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/content/StyleTTS2/train_finetune.py", line 302, in main
    s = model.predictor_encoder(mel.unsqueeze(0).unsqueeze(1))
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/parallel/data_parallel.py", line 183, in forward
    return self.module(*inputs[0], **module_kwargs[0])
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/content/StyleTTS2/models.py", line 160, in forward
    h = self.shared(x)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/container.py", line 215, in forward
    input = module(input)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Calculated padded input size per channel: (5 x 4). Kernel size: (5 x 5). Kernel size can't be greater than actual input 
```

I was actually getting this error when I tried to train StyleTTS2 from scratch on another machine with this dataset. Is that a dataset problem or a bug?

**Comment by yl4579** [comment]
See #48 #80 #81
