### ISSUE TITLE
Finetuning kernel size issue

### ISSUE THREAD

**Issue by rlenain** [yl4579/StyleTTS2#180]
Hello there,

I am trying to finetune a model on my own data. I have preprocessed the dataset using the phonemizer. In order to get the model to work on my GPU settings, I have to bring down the `batch_size` to 2 and the `max_len` to 200. When I run the command for finetuning, after some iterations, I get the following error:

```bash
RuntimeError: Calculated padded input size per channel: (5 x 4). Kernel size: (5 x 5). Kernel size can't be greater than actual input size
```

The whole trace looks more like this:
```bash
Epoch [1/50], Step [10/2580], Loss: 0.31066, Disc Loss: 3.97106, Dur Loss: 0.57450, CE Loss: 0.02465, Norm Loss: 0.47254, F0 Loss: 1.82381, LM Loss: 1.53184, Gen Loss: 7.19418, Sty Loss: 0.00000, Diff Loss: 0.00000, DiscLM Loss: 0.00000, GenLM Loss: 0.00000, SLoss: 0.00000, S2S Loss: 0.61299, Mono Loss: 0.09038
Time elasped: 10.649187564849854
Epoch [1/50], Step [20/2580], Loss: 0.28693, Disc Loss: 3.94578, Dur Loss: 0.69617, CE Loss: 0.03821, Norm Loss: 0.35513, F0 Loss: 1.25693, LM Loss: 1.16231, Gen Loss: 6.54411, Sty Loss: 0.00000, Diff Loss: 0.00000, DiscLM Loss: 0.00000, GenLM Loss: 0.00000, SLoss: 0.00000, S2S Loss: 0.45227, Mono Loss: 0.05663
Time elasped: 19.195926189422607
Traceback (most recent call last):
  File "/home/raph/repos/StyleTTS2/train_finetune.py", line 707, in <module>
    main()
  File "/home/raph/miniconda3/envs/styletts2/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/raph/miniconda3/envs/styletts2/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/raph/miniconda3/envs/styletts2/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/raph/miniconda3/envs/styletts2/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/raph/repos/StyleTTS2/train_finetune.py", line 302, in main
    s = model.predictor_encoder(mel.unsqueeze(0).unsqueeze(1))
  File "/home/raph/miniconda3/envs/styletts2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/raph/miniconda3/envs/styletts2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/raph/miniconda3/envs/styletts2/lib/python3.9/site-packages/torch/nn/parallel/data_parallel.py", line 183, in forward
    return self.module(*inputs[0], **module_kwargs[0])
  File "/home/raph/miniconda3/envs/styletts2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/raph/miniconda3/envs/styletts2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/raph/repos/StyleTTS2/models.py", line 160, in forward
    h = self.shared(x)
  File "/home/raph/miniconda3/envs/styletts2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/raph/miniconda3/envs/styletts2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/raph/miniconda3/envs/styletts2/lib/python3.9/site-packages/torch/nn/modules/container.py", line 215, in forward
    input = module(input)
  File "/home/raph/miniconda3/envs/styletts2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/raph/miniconda3/envs/styletts2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1568, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/home/raph/miniconda3/envs/styletts2/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/raph/miniconda3/envs/styletts2/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Calculated padded input size per channel: (5 x 4). Kernel size: (5 x 5). Kernel size can't be greater than actual input size
```

Any thoughts? Thank you.

**Comment by rlenain** [comment]
Turns out the issue was that I had some files which were too short. I solved it by removing any audio files shorter than 1 second.
