### ISSUE TITLE
self._shortcut(x) + self._residual(x) - The size of tensor a (34) must match the size of tensor b (35) at non-singleton dimension 2

### ISSUE THREAD

**Issue by gooofy** [yl4579/StyleTTS2#208]
Sorry if this is a dumb issue, I don't exactly know what I am doing here - but I thought maybe you can give me a hint anyways:

I am trying to train a german StyleTTS2 model. So far I (think I) have german-only Tokenizer, PL-BERT and AuxillaryASR models ready (I can share those if it helps). Since this is german-only and I am training on graphemes instead of phonemes (in my - very limited - experience espeak-ng and others do a pretty bad job at phonemizing german and since german script is pretty close to pronounciations at times I though I'd give graphemes a try here). Because of this I had to modify the text utilities used as well as some of the parameters here and there.

Now I have run into an issue: when I try to launch train_first, I get this:

     File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
        return self._call_impl(*args, **kwargs)
      File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
        return forward_call(*args, **kwargs)
      File "/home/guenter/projects/hal9000/ennis/chat/src/StyleTTS2/models.py", line 136, in forward
        return forward_call(*args, **kwargs)
      File "/home/guenter/projects/hal9000/ennis/chat/src/StyleTTS2/models.py", line 136, in forward
        x = self._shortcut(x) + self._residual(x)
    RuntimeError: The size of tensor a (34) must match the size of tensor b (35) at non-singleton dimension 2
        x = self._shortcut(x) + self._residual(x)
    RuntimeError: The size of tensor a (34) must match the size of tensor b (35) at non-singleton dimension 2
    [2024-03-03 15:31:36,364] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 42841) of binary: /home/guenter/projects/hal9000/ennis/chat/venv/bin/python3

here is my config yml:

    log_dir: "Models/de"
    lang: "de"
    first_stage_path: "first_stage.pth"
    save_freq: 1
    log_interval: 10
    device: "cuda"
    epochs_1st: 50 # number of epochs for first stage training (pre-training)
    epochs_2nd: 30 # number of peochs for second stage training (joint training)
    batch_size: 16
    max_len: 300 # maximum number of frames
    pretrained_model: ""
    second_stage_load_pretrained: true # set to true if the pre-trained model is for 2nd stage
    load_only_params: false # set to true if do not want to load epoch numbers and optimizer parameters
    
    F0_path: "Utils/JDC/bst.t7"
    ASR_config: "Utils/ASR.de/config.yml"
    ASR_path: "Utils/ASR.de/epoch_00053.pth"
    PLBERT_dir: 'Utils/PLBERT.de/'
    
    data_params:
      train_data: "Data.de/train_list.txt"
      val_data: "Data.de/val_list.txt"
      root_path: "/home/guenter/projects/hal9000/ennis/voices/src"
      OOD_data: "Data.de/OOD_texts.txt"
      min_length: 50 # sample until texts with this size are obtained for OOD texts
    
    preprocess_params:
      sr: 24000
    #  spect_params:
    #    n_fft: 2048
    #    win_length: 1200
    #    hop_length: 300
    
    mel_params:
       n_mels: 138
       n_fft: 2048
       win_length: 1200
       hop_length: 300
    
    model_params:
      multispeaker: true
    
      dim_in: 64
      hidden_dim: 512
      max_conv_dim: 512
      n_layer: 3
      n_mels: 80
    
      n_token: 138 # number of phoneme tokens
      max_dur: 50 # maximum duration of a single phoneme
      style_dim: 128 # style vector size
    
      dropout: 0.2
    
      # config for decoder
      decoder:
          type: 'hifigan' # either hifigan or istftnet
          resblock_kernel_sizes: [3,7,11]
          upsample_rates :  [10,5,3,2]
          upsample_initial_channel: 512
          resblock_dilation_sizes: [[1,3,5], [1,3,5], [1,3,5]]
          upsample_kernel_sizes: [20,10,6,4]
    
      # speech language model config
      slm:
          model: 'microsoft/wavlm-base-plus'
          sr: 16000 # sampling rate of SLM
          hidden: 768 # hidden size of SLM
          nlayers: 13 # number of layers of SLM
          initial_channel: 64 # initial channels of SLM discriminator head
    
      # style diffusion model config
      diffusion:
        embedding_mask_proba: 0.1
        # transformer config
        transformer:
          num_layers: 3
          num_heads: 8
          head_features: 64
          multiplier: 2
    
        # diffusion distribution config
        dist:
          sigma_data: 0.2 # placeholder for estimate_sigma_data set to false
          estimate_sigma_data: true # estimate sigma_data from the current batch if set to true
          mean: -3.0
          std: 1.0
    
    loss_params:
        lambda_mel: 5. # mel reconstruction loss
        lambda_gen: 1. # generator loss
        lambda_slm: 1. # slm feature matching loss
    
        lambda_mono: 1. # monotonic alignment loss (1st stage, TMA)
        lambda_s2s: 1. # sequence-to-sequence loss (1st stage, TMA)
        TMA_epoch: 5 # TMA starting epoch (1st stage)
    
        lambda_F0: 1. # F0 reconstruction loss (2nd stage)
        lambda_norm: 1. # norm reconstruction loss (2nd stage)
        lambda_dur: 1. # duration loss (2nd stage)
        lambda_ce: 20. # duration predictor probability output CE loss (2nd stage)
        lambda_sty: 1. # style reconstruction loss (2nd stage)
        lambda_diff: 1. # score matching loss (2nd stage)
    
        diff_epoch: 10 # style diffusion starting epoch (2nd stage)
        joint_epoch: 15 # joint training starting epoch (2nd stage)
    
    optimizer_params:
      lr: 0.0001 # general learning rate
      bert_lr: 0.00001 # learning rate for PLBERT
      ft_lr: 0.00001 # learning rate for acoustic modules
    
    slmadv_params:
      min_len: 400 # minimum length of samples
      max_len: 500 # maximum length of samples
      batch_percentage: 0.5 # to prevent out of memory, only use half of the original batch size
      iter: 20 # update the discriminator every this iterations of generator update
      thresh: 5 # gradient norm above which the gradient is scaled
      scale: 0.01 # gradient scaling factor for predictors from SLM discriminators
      sig: 1.5 # sigma for differentiable duration modeling

at first glance - do you see anything obviously wrong esp with my model params or anything I could look into to get this working?

**Comment by yl4579** [comment]
Can you provide more traceback? Like where in train.py does this error occur?

**Comment by gooofy** [comment]
Thanks for looking into this :)

here is the complete output from my training attempt:

    guenter@hal ~/projects/hal9000/ennis/chat/src/StyleTTS2 $ accelerate launch train_first.py --config_path ./Configs/config_de.yml
    The following values were not passed to `accelerate launch` and had defaults used instead:
    	`--num_processes` was set to a value of `2`
    		More than one GPU was found, enabling multi-GPU training.
    		If this was unintended please pass in `--num_processes=1`.
    	`--num_machines` was set to a value of `1`
    	`--mixed_precision` was set to a value of `'no'`
    	`--dynamo_backend` was set to a value of `'no'`
    To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
    [W Utils.hpp:133] Warning: Environment variable TORCH_NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function getCvarInt)
    [W Utils.hpp:133] Warning: Environment variable TORCH_NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function getCvarInt)
    [rank1]:[W Utils.hpp:106] Warning: Environment variable TORCH_NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function getCvarString)
    [rank0]:[W Utils.hpp:106] Warning: Environment variable TORCH_NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function getCvarString)
    [rank0]:[W Utils.hpp:106] Warning: Environment variable TORCH_NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function getCvarString)
    [rank1]:[W Utils.hpp:106] Warning: Environment variable TORCH_NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function getCvarString)
    [rank0]:[W Utils.hpp:106] Warning: Environment variable TORCH_NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function getCvarString)
    [rank1]:[W Utils.hpp:106] Warning: Environment variable TORCH_NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function getCvarString)
    [rank1]:[W Utils.hpp:106] Warning: Environment variable TORCH_NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function getCvarString)
    [rank0]:[W Utils.hpp:106] Warning: Environment variable TORCH_NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function getCvarString)
    [rank0]:[W Utils.hpp:106] Warning: Environment variable TORCH_NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function getCvarString)
    [rank1]:[W Utils.hpp:106] Warning: Environment variable TORCH_NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function getCvarString)
    [rank0]:[W Utils.hpp:106] Warning: Environment variable TORCH_NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function getCvarString)
    [rank1]:[W Utils.hpp:106] Warning: Environment variable TORCH_NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function getCvarString)
    [rank1]:[W Utils.hpp:106] Warning: Environment variable TORCH_NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function getCvarString)
    [rank0]:[W Utils.hpp:106] Warning: Environment variable TORCH_NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function getCvarString)
    [rank0]:[W Utils.hpp:106] Warning: Environment variable TORCH_NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function getCvarString)
    [rank1]:[W Utils.hpp:106] Warning: Environment variable TORCH_NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function getCvarString)
    [rank0]:[W Utils.hpp:106] Warning: Environment variable TORCH_NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function getCvarString)
    [rank1]:[W Utils.hpp:106] Warning: Environment variable TORCH_NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function getCvarString)
    [rank1]:[W Utils.hpp:106] Warning: Environment variable TORCH_NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function getCvarString)
    [rank0]:[W Utils.hpp:106] Warning: Environment variable TORCH_NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function getCvarString)
    [rank0]:[W Utils.hpp:106] Warning: Environment variable TORCH_NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function getCvarString)
    [rank1]:[W Utils.hpp:106] Warning: Environment variable TORCH_NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function getCvarString)
    [rank0]:[W Utils.hpp:106] Warning: Environment variable TORCH_NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function getCvarString)
    [rank1]:[W Utils.hpp:106] Warning: Environment variable TORCH_NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function getCvarString)
    [rank0]:[W Utils.hpp:106] Warning: Environment variable TORCH_NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function getCvarString)
    [rank1]:[W Utils.hpp:106] Warning: Environment variable TORCH_NCCL_ASYNC_ERROR_HANDLING is deprecated; use TORCH_NCCL_ASYNC_ERROR_HANDLING instead (function getCvarString)
    Some weights of the model checkpoint at microsoft/wavlm-base-plus were not used when initializing WavLMModel: ['encoder.pos_conv_embed.conv.weight_v', 'encoder.pos_conv_embed.conv.weight_g']
    - This IS expected if you are initializing WavLMModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
    - This IS NOT expected if you are initializing WavLMModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
    Some weights of WavLMModel were not initialized from the model checkpoint at microsoft/wavlm-base-plus and are newly initialized: ['encoder.pos_conv_embed.conv.parametrizations.weight.original1', 'encoder.pos_conv_embed.conv.parametrizations.weight.original0']
    You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
    Some weights of the model checkpoint at microsoft/wavlm-base-plus were not used when initializing WavLMModel: ['encoder.pos_conv_embed.conv.weight_v', 'encoder.pos_conv_embed.conv.weight_g']
    - This IS expected if you are initializing WavLMModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
    - This IS NOT expected if you are initializing WavLMModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
    Some weights of WavLMModel were not initialized from the model checkpoint at microsoft/wavlm-base-plus and are newly initialized: ['encoder.pos_conv_embed.conv.parametrizations.weight.original1', 'encoder.pos_conv_embed.conv.parametrizations.weight.original0']
    You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
    [rank1]:[W reducer.cpp:1360] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
    [rank0]:[W reducer.cpp:1360] Warning: find_unused_parameters=True was specified in DDP constructor, but did not find any unused parameters in the forward pass. This flag results in an extra traversal of the autograd graph every iteration,  which can adversely affect performance. If your model indeed never has any unused parameters in the forward pass, consider turning this flag off. Note that this warning may be a false positive if your model has flow control causing later iterations to have unused parameters. (function operator())
    Traceback (most recent call last):
      File "/home/guenter/projects/hal9000/ennis/chat/src/StyleTTS2/train_first.py", line 452, in <module>
        main()
      File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    Traceback (most recent call last):
      File "/home/guenter/projects/hal9000/ennis/chat/src/StyleTTS2/train_first.py", line 452, in <module>
        main()
      File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
        return self.main(*args, **kwargs)
          File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    return self.main(*args, **kwargs)
      File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
        rv = self.invoke(ctx)
          File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    rv = self.invoke(ctx)
      File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
        return ctx.invoke(self.callback, **ctx.params)
        return ctx.invoke(self.callback, **ctx.params)  File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    
      File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
        return __callback(*args, **kwargs)
      File "/home/guenter/projects/hal9000/ennis/chat/src/StyleTTS2/train_first.py", line 260, in main
        return __callback(*args, **kwargs)
      File "/home/guenter/projects/hal9000/ennis/chat/src/StyleTTS2/train_first.py", line 260, in main
        s = model.style_encoder(st.unsqueeze(1) if multispeaker else gt.unsqueeze(1))
        s = model.style_encoder(st.unsqueeze(1) if multispeaker else gt.unsqueeze(1))
      File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
      File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
      File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
        return self._call_impl(*args, **kwargs)
      File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
        return forward_call(*args, **kwargs)
          File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1523, in forward
    return forward_call(*args, **kwargs)
      File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1523, in forward
            else self._run_ddp_forward(*inputs, **kwargs)else self._run_ddp_forward(*inputs, **kwargs)
    
      File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1359, in _run_ddp_forward
      File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/torch/nn/parallel/distributed.py", line 1359, in _run_ddp_forward
            return self.module(*inputs, **kwargs)  # type: ignore[index]return self.module(*inputs, **kwargs)  # type: ignore[index]
    
      File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
      File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
        return self._call_impl(*args, **kwargs)
    return self._call_impl(*args, **kwargs)
      File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
      File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
            return forward_call(*args, **kwargs)return forward_call(*args, **kwargs)
    
      File "/home/guenter/projects/hal9000/ennis/chat/src/StyleTTS2/models.py", line 160, in forward
      File "/home/guenter/projects/hal9000/ennis/chat/src/StyleTTS2/models.py", line 160, in forward
            h = self.shared(x)h = self.shared(x)
    
      File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
      File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
            return self._call_impl(*args, **kwargs)return self._call_impl(*args, **kwargs)
    
      File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
      File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
            return forward_call(*args, **kwargs)return forward_call(*args, **kwargs)
    
      File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
      File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/torch/nn/modules/container.py", line 217, in forward
            input = module(input)input = module(input)
    
      File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
      File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
            return self._call_impl(*args, **kwargs)return self._call_impl(*args, **kwargs)
    
      File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
      File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
            return forward_call(*args, **kwargs)return forward_call(*args, **kwargs)
    
      File "/home/guenter/projects/hal9000/ennis/chat/src/StyleTTS2/models.py", line 136, in forward
      File "/home/guenter/projects/hal9000/ennis/chat/src/StyleTTS2/models.py", line 136, in forward
            x = self._shortcut(x) + self._residual(x)x = self._shortcut(x) + self._residual(x)
    
    RuntimeErrorRuntimeError: : The size of tensor a (34) must match the size of tensor b (35) at non-singleton dimension 2The size of tensor a (34) must match the size of tensor b (35) at non-singleton dimension 2
    
    [2024-03-07 08:08:38,991] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 2345) of binary: /home/guenter/projects/hal9000/ennis/chat/venv/bin/python3
    Traceback (most recent call last):
      File "/home/guenter/projects/hal9000/ennis/chat/venv/bin/accelerate", line 8, in <module>
        sys.exit(main())
      File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 47, in main
        args.func(args)
      File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 1008, in launch_command
        multi_gpu_launcher(args)
      File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/accelerate/commands/launch.py", line 666, in multi_gpu_launcher
        distrib_run.run(args)
      File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/torch/distributed/run.py", line 803, in run
        elastic_launch(
      File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
        return launch_agent(self._config, self._entrypoint, list(args))
      File "/home/guenter/projects/hal9000/ennis/chat/venv/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
        raise ChildFailedError(
    torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
    ============================================================
    train_first.py FAILED
    ------------------------------------------------------------
    Failures:
    [1]:
      time      : 2024-03-07_08:08:38
      host      : hal
      rank      : 1 (local_rank: 1)
      exitcode  : 1 (pid: 2346)
      error_file: <N/A>
      traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
    ------------------------------------------------------------
    Root Cause (first observed failure):
    [0]:
      time      : 2024-03-07_08:08:38
      host      : hal
      rank      : 0 (local_rank: 0)
      exitcode  : 1 (pid: 2345)
      error_file: <N/A>
      traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
    ============================================================

I have pushed my modified code to github for reference:

https://github.com/gooofy/StyleTTS2

I can also provide my modified code for PL-BERT and AuxillaryASR if that helps

**Comment by lexkoro** [comment]
It's because of the downsample https://github.com/gooofy/StyleTTS2/blob/7711ab5b75ad7670366c96c29a8c95493abd9d4c/models.py#L73

It seems you are using a different value for mel channels. Default is 80. You can fix it just like with the width by concatenating the last value to the end of the tensor.

**Comment by gooofy** [comment]
You're right, mel channes was the issue! Thanks you so much for looking into this, closing the issue.

Unfortunately it looks like my 12GB Titan X is not capable of training StyleTTS2, so the journey seems to end here for me, at least for now.
