### ISSUE TITLE
Attempting to continue Finetuning

### ISSUE THREAD

**Issue by IIEleven11** [yl4579/StyleTTS2#72]
Hi, awesome stuff so far thank you! I am running into a speed bump though. While using your train_finetune.py script on my own dataset. I have made it to epoch 109 the model sounds pretty good and I was hoping to continue tuning except I cannot seem to get past epoch 110 step ~98/99. I started with batch size of 10 and have tried lowering it a few times, I am currently just trying to work at a batch size of 4 incase there are possible memory issues. 
         
Within my config I adjusted the "pretrained_model: Models/LibriTTS/epoch_2nd_00109.pth", made sure "second_stage_load_pretrained: true" was true and had to set  "load_only_params: false" from true to false as the "load_checkpoint" function in "train_finetune.py" only loads the model parameters and ignores the epoch and iteration numbers saved in the checkpoint. 
     
I am using a single RTX A6000. Any guidance would be greatly appreciated, thank you! Here is the complete traceback followed by my config:

Traceback (most recent call last):
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/train_finetune.py", line 714, in <module>
    main()
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/train_finetune.py", line 509, in main
    loss_gen_lm.backward()
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 1, 1]] is at version 3; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

After adding "torch.autograd.set_detect_anomaly(True)"

Traceback (most recent call last):
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/train_finetune.py", line 716, in <module>
    main()
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/train_finetune.py", line 511, in main
    loss_gen_lm.backward()
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 1, 1]] is at version 3; expected version 1 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!

config_ft.yml:

{ASR_config: Utils/ASR/config.yml, ASR_path: Utils/ASR/epoch_00080.pth, F0_path: Utils/JDC/bst.t7,
  PLBERT_dir: Utils/PLBERT/, batch_size: 4, data_params: {OOD_data: /home/Ubuntu/WORK/StyleTTS2/Data/OOD_texts.txt,
    min_length: 50, root_path: /home/Ubuntu/WORK/StyleTTS2/Data/wavs, train_data: /home/Ubuntu/WORK/StyleTTS2/Data/train_list.txt,
    val_data: /home/Ubuntu/WORK/StyleTTS2/Data/val_list.txt}, device: cuda, epochs: 200,
  load_only_params: false, log_dir: Models/LJSpeech, log_interval: 10, loss_params: {
    diff_epoch: 10, joint_epoch: 110, lambda_F0: 1.0, lambda_ce: 20.0, lambda_diff: 1.0,
    lambda_dur: 1.0, lambda_gen: 1.0, lambda_mel: 5.0, lambda_mono: 1.0, lambda_norm: 1.0,
    lambda_s2s: 1.0, lambda_slm: 1.0, lambda_sty: 1.0}, max_len: 100, model_params: {
    decoder: {resblock_dilation_sizes: [[1, 3, 5], [1, 3, 5], [1, 3, 5]], resblock_kernel_sizes: [
        3, 7, 11], type: hifigan, upsample_initial_channel: 512, upsample_kernel_sizes: [
        20, 10, 6, 4], upsample_rates: [10, 5, 3, 2]}, diffusion: {dist: {estimate_sigma_data: true,
        mean: -3.0, sigma_data: 0.2, std: 1.0}, embedding_mask_proba: 0.1, transformer: {
        head_features: 64, multiplier: 2, num_heads: 8, num_layers: 3}}, dim_in: 64,
    dropout: 0.2, hidden_dim: 512, max_conv_dim: 512, max_dur: 50, multispeaker: true,
    n_layer: 3, n_mels: 80, n_token: 178, slm: {hidden: 768, initial_channel: 64,
      model: microsoft/wavlm-base-plus, nlayers: 13, sr: 16000}, style_dim: 128},
  optimizer_params: {bert_lr: 1.0e-05, ft_lr: 0.0001, lr: 0.0001}, preprocess_params: {
    spect_params: {hop_length: 300, n_fft: 2048, win_length: 1200}, sr: 24000}, pretrained_model: Models/LibriTTS/epoch_2nd_00109.pth,
  save_freq: 20, second_stage_load_pretrained: true, slmadv_params: {batch_percentage: 0.5,
    iter: 10, max_len: 500, min_len: 400, scale: 0.01, sig: 1.5, thresh: 5}}

**Comment by devidw** [comment]
run into the same issue during fine-tuning around epoch 30 of a 36 min dataset using h100:

```
Traceback (most recent call last):
  File "./train_finetune.py", line 714, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "./train_finetune.py", line 509, in main
    loss_gen_lm.backward()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/ubuntu/.local/lib/python3.8/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 1, 1]] is at version 3; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```

**Comment by kmn1024** [comment]
I had the same issue here: https://github.com/yl4579/StyleTTS2/issues/73

The issue appears to be here: https://github.com/yl4579/StyleTTS2/blob/main/train_finetune.py#L504. Changing it to `d_loss_slm.backward(retain_graph=True)` seems to fix the problem.

retain_graph=True is necessary because the graph gets deleted after backward() pass to save memory. But you need the graph for the loss_gen_lm.backward() call.

**Comment by IIEleven11** [comment]
I will try it now

**Comment by IIEleven11** [comment]
Almost made it, it appears that this is possibly because I am using a single GPU. Traceback points to these lines 34-39 in train_finetune.py. I did move back to batch_size 10. Then tried with a size of 6 and 8 with it throwing the original error.

class MyDataParallel(torch.nn.DataParallel):
    def __getattr__(self, name):
        try:
            return super().__getattr__(name)
        except AttributeError:
            return getattr(self.module, name)

Traceback (most recent call last):
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/train_finetune.py", line 714, in <module>
    main()
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/train_finetune.py", line 487, in main
    slm_out = slmadv(i, 
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/Modules/slmadv.py", line 138, in forward
    y_pred = self.model.decoder(en, F0_fake, N_fake, sp[:, :128])
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/torch/nn/parallel/data_parallel.py", line 183, in forward
    return self.module(*inputs[0], **module_kwargs[0])
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/Modules/hifigan.py", line 474, in forward
    x = self.generator(x, s, F0_curve)
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/Modules/hifigan.py", line 339, in forward
    xs = self.resblocks[i*self.num_kernels+j](x, s)
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/Modules/hifigan.py", line 70, in forward
    xt = n2(xt, s)
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/Modules/hifigan.py", line 24, in forward
    return (1 + gamma) * self.norm(x) + beta
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/torch/nn/modules/instancenorm.py", line 87, in forward
    return self._apply_instance_norm(input)
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/torch/nn/modules/instancenorm.py", line 36, in _apply_instance_norm
    return F.instance_norm(
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/torch/nn/functional.py", line 2523, in instance_norm
    return torch.instance_norm(
RuntimeError: NVML_SUCCESS == DriverAPI::get()->nvmlInit_v2_() INTERNAL ASSERT FAILED at "../c10/cuda/CUDACachingAllocator.cpp":1123, please report a bug to PyTorch. 



Batch size 8 and 4 traceback

Traceback (most recent call last):
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/train_finetune.py", line 714, in <module>
    main()
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/train_finetune.py", line 509, in main
    loss_gen_lm.backward()
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/torch/_tensor.py", line 492, in backward
    torch.autograd.backward(
  File "/home/Ubuntu/WORK/StyleTTS2/Colab/venv/lib/python3.10/site-packages/torch/autograd/__init__.py", line 251, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [1, 1, 1]] is at version 3; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

**Comment by IIEleven11** [comment]
Problem might be on my end, reinstalling cuda toolkit now

**Comment by kmn1024** [comment]
Sorry one more change is needed to get this to work! See https://github.com/yl4579/StyleTTS2/pull/74.

**Comment by IIEleven11** [comment]
That worked, thank you!

**Comment by yl4579** [comment]
Should be solved now.
