### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 38: character maps to <undefined> - Any help please.

### ISSUE THREAD

**Issue by rikabi89** [yl4579/StyleTTS2#88]
(StyleTTS2) H:\StyleTTS2>python train_finetune.py --config_path ./Configs/config_ft.yml

Traceback (most recent call last):
  File "train_finetune.py", line 707, in <module>
    main()
  File "H:\anaconda3\envs\StyleTTS2\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "H:\anaconda3\envs\StyleTTS2\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "H:\anaconda3\envs\StyleTTS2\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "H:\anaconda3\envs\StyleTTS2\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "train_finetune.py", line 100, in main
    device=device)
  File "H:\StyleTTS2\meldataset.py", line 244, in build_dataloader
    dataset = FilePathDataset(path_list, root_path, OOD_data=OOD_data, min_length=min_length, validation=validation, **dataset_config)
  File "H:\StyleTTS2\meldataset.py", line 97, in __init__
    tl = f.readlines()
  File "H:\anaconda3\envs\StyleTTS2\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 38: character maps to <undefined>

(StyleTTS2) H:\StyleTTS2>

[val_list.txt](https://github.com/yl4579/StyleTTS2/files/13467542/val_list.txt)
[train_list.txt](https://github.com/yl4579/StyleTTS2/files/13467543/train_list.txt)
[OOD_texts.txt](https://github.com/yl4579/StyleTTS2/files/13467544/OOD_texts.txt)

![image](https://github.com/yl4579/StyleTTS2/assets/85737703/b096776f-9d75-4833-bf37-29e8956b52ea)

**Comment by Kreevoz** [comment]
Check out these notes #81 and set the right environment variable if you wanna do this under Windows.
