### ISSUE TITLE
trying mixed precision on 16gb *4080 finetune

### ISSUE THREAD

**Issue by rikabi89** [yl4579/StyleTTS2#96]
`(StyleTTS2) H:\StyleTTS2>accelerate launch --mixed_precision=fp16 train_first.py --config_path ./Configs/config_ft.yml
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `1`
        `--num_machines` was set to a value of `1`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Traceback (most recent call last):
  File "H:\anaconda3\envs\StyleTTS2\lib\site-packages\munch\__init__.py", line 116, in __getattr__
    return object.__getattribute__(self, k)
AttributeError: 'Munch' object has no attribute 'TMA_epoch'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\anaconda3\envs\StyleTTS2\lib\site-packages\munch\__init__.py", line 119, in __getattr__
    return self[k]
KeyError: 'TMA_epoch'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_first.py", line 444, in <module>
    main()
  File "H:\anaconda3\envs\StyleTTS2\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "H:\anaconda3\envs\StyleTTS2\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "H:\anaconda3\envs\StyleTTS2\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "H:\anaconda3\envs\StyleTTS2\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "train_first.py", line 131, in main
    TMA_epoch = loss_params.TMA_epoch
  File "H:\anaconda3\envs\StyleTTS2\lib\site-packages\munch\__init__.py", line 121, in __getattr__
    raise AttributeError(k)
AttributeError: TMA_epoch
Traceback (most recent call last):
  File "H:\anaconda3\envs\StyleTTS2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "H:\anaconda3\envs\StyleTTS2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "H:\anaconda3\envs\StyleTTS2\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "H:\anaconda3\envs\StyleTTS2\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "H:\anaconda3\envs\StyleTTS2\lib\site-packages\accelerate\commands\launch.py", line 941, in launch_command
    simple_launcher(args)
  File "H:\anaconda3\envs\StyleTTS2\lib\site-packages\accelerate\commands\launch.py", line 603, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['H:\\anaconda3\\envs\\StyleTTS2\\python.exe', 'train_first.py', '--config_path', './Configs/config_ft.yml']' returned non-zero exit status 1.`

So it works without mixed precision but its extremely slow. Anything I can do optimise vram other than reduce batche size?  Win11 Anaconda

**Comment by rikabi89** [comment]
Also I tried FP8 and got : 

```
(StyleTTS2) H:\StyleTTS2>accelerate launch --mixed_precision=fp8 train_first.py --config_path ./Configs/config_ft1.yml
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_processes` was set to a value of `1`
        `--num_machines` was set to a value of `1`
        `--dynamo_backend` was set to a value of `'no'`
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Traceback (most recent call last):
  File "train_first.py", line 445, in <module>
    main()
  File "H:\anaconda3\envs\StyleTTS2\lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "H:\anaconda3\envs\StyleTTS2\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "H:\anaconda3\envs\StyleTTS2\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "H:\anaconda3\envs\StyleTTS2\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "train_first.py", line 50, in main
    accelerator = Accelerator(project_dir=log_dir, split_batches=True, kwargs_handlers=[ddp_kwargs])
  File "H:\anaconda3\envs\StyleTTS2\lib\site-packages\accelerate\accelerator.py", line 353, in __init__
    **kwargs,
  File "H:\anaconda3\envs\StyleTTS2\lib\site-packages\accelerate\state.py", line 691, in __init__
    raise ValueError("Using `fp8` precision requires `transformer_engine` to be installed.")
ValueError: Using `fp8` precision requires `transformer_engine` to be installed.
Traceback (most recent call last):
  File "H:\anaconda3\envs\StyleTTS2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "H:\anaconda3\envs\StyleTTS2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "H:\anaconda3\envs\StyleTTS2\Scripts\accelerate.exe\__main__.py", line 7, in <module>
  File "H:\anaconda3\envs\StyleTTS2\lib\site-packages\accelerate\commands\accelerate_cli.py", line 45, in main
    args.func(args)
  File "H:\anaconda3\envs\StyleTTS2\lib\site-packages\accelerate\commands\launch.py", line 941, in launch_command
    simple_launcher(args)
  File "H:\anaconda3\envs\StyleTTS2\lib\site-packages\accelerate\commands\launch.py", line 603, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['H:\\anaconda3\\envs\\StyleTTS2\\python.exe', 'train_first.py', '--config_path', './Configs/config_ft1.yml']' returned non-zero exit status 1.
```

But I assume this does not work on Windows

**Comment by yl4579** [comment]
No you can’t finetune using train_first.py. Since train_finetune.py uses DP, I think implementing mixed precision using native pytorch library should work. If someone can help with it it’d be great.

**Comment by yl4579** [comment]
@rikabi89 wait, I think you can actually change the DP to accelerate if you only have one GPU and do `mixed_precision`. You only need to do these changes: https://huggingface.co/docs/accelerate/package_reference/accelerator

**Comment by rikabi89** [comment]
> @rikabi89 wait, I think you can actually change the DP to accelerate if you only have one GPU and do `mixed_precision`. You only need to do these changes: https://huggingface.co/docs/accelerate/package_reference/accelerator

I have no idea how to imeplent this unfortunately. But I saw your other post, hopefully someone knowledgeable can sort it.
