### ISSUE TITLE
Trying to fine tune with SLM adversarial training

### ISSUE THREAD

**Issue by jazza420** [yl4579/StyleTTS2#99]
training starts off fine but when I get to the joint_epoch i get the following issue:

Traceback (most recent call last):
  File "/workspace/StyleTTS2/train_finetune.py", line 707, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/workspace/StyleTTS2/train_finetune.py", line 493, in main
    ref_lengths, use_ind, s_trg.detach(), ref if multispeaker else None)
UnboundLocalError: local variable 'ref' referenced before assignment

can anyone help me? am i missing something? thanks

**Comment by yl4579** [comment]
Your `diff_epoch` is bigger than `joint_epoch`.

**Comment by GUUser91** [comment]
@jazza420 
I found a workaround by setting multispeaker to false.

@yl4579
Is setting multispeaker to false a bad idea if I try to fine tune with SLM adversarial training on a diffusion trained model as the base model?
